### PR TITLE
Add rmv feature

### PR DESCRIPTION
**Pull request by Alfredbis29**
**In This Project  I:**

- Remove all hardcoded items from the tasks array.
- Create a new JavaScript file for the new functionality.
- Implement a function for adding a new task (add a new element to the array).
- Implement a function for deleting a task (remove an element from the array).
- Implement a function for editing task descriptions.
- By default new tasks should have the property completed set to false and the property index set to the value of the new array length (i.e. if you're adding a 5th task to the list, the index of that task should equal 5).
- Deleting a task should update all remaining items' indexes, so they represent the current list order and are unique.
- All changes to the To-Do List should be saved in local storage.

### CODE REVIEW

**Review by mikethreels — CHANGES_REQUESTED** [review]
Hi Alfred, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._
- [ ] according to the requirements there should be a function for editing task descriptions as well, please implement this.
- [x] please make sure to use[ the template](https://github.com/microverseinc/readme-template) for the readme file provided by Microverse, including the links (for example to the MIT license). keep in mind that all sections of the template are mandatory except for the "Live Demo", "Run Tests" and "Deployment" sections, these are only mandatory if the specific project you're working on requires it.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alfredbis29** [comment]
I used the template for the readme file provided by Microverse, and I structured everything!
Please check again in my readme file.

**Comment by Alfredbis29** [comment]
**Now I implemented the function for editing task descriptions.** 
You can now check! Thanks for checking.

**Comment by mikethreels** [comment]
Hi Alfred,
It is possible I made a mistake including the readme file in the required changes, however, I'm not able to check it properly right now because I don't have access to my computer at the moment, in case you followed all the readme requirements correctly I suggest you send it for review again as soon as you're done implementing the other changes.

**Comment by Alfredbis29** [comment]
Hello Michael Threes, 
It's okay, and I have already implemented the editing function in my project. 
Thanks for the code review

**Review by Kingstalux — APPROVED** [review]
Hi @Alfredbis29,
# Status: Approved ✔️ ✔️ ✔️ 
 
Gu2dpSp0qee4C710M5kVsWN425J3-vv2w52by6

Good job implementing the required changes 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alfredbis29** [comment]
Thanks so much, Ngu Kingsley Junior Cho, for the improvement on the project which really stresses me! thanks so much

**Pull request merged**
